#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
domaines.py

Domaine web officiel de chaque entreprise de la liste.

POURQUOI CE FICHIER
Deviner 'sncf.com' depuis "SNCF" marche. Deviner 'lesmousquetaires.com'
depuis "Les Mousquetaires" ne marche pas. Or le domaine est la cle qui
ouvre les portails maison : on teste carrieres.{domaine}, emploi.{domaine},
jobs.{domaine}, on suit les redirections, et on lit la signature de l'ATS
qui se cache derriere. Beaucoup de portails "maison" ne sont qu'une facade
devant un Taleo, un SuccessFactors ou un Cornerstone.

Les entreprises absentes de ce dictionnaire sont devinees depuis leur nom.
"""

DOMAINES = {
    # --- RH & Staffing ---
    'Randstad France': 'randstad.fr',
    'Adecco France': 'adecco.fr',
    'ManpowerGroup France': 'manpower.fr',
    'Hays France': 'hays.fr',
    'PageGroup France': 'pagegroup.com',
    'Michael Page France': 'michaelpage.fr',
    'Robert Half France': 'roberthalf.fr',
    'Gi Group France': 'gigroup.fr',
    'Synergie': 'synergie.fr',
    'Proman': 'proman-emploi.fr',
    'Crit Group': 'groupe-crit.com',
    'Actual Group': 'groupeactual.eu',
    'Expectra': 'expectra.fr',
    'Kelly Services France': 'kellyservices.fr',
    'Fed Group': 'fedgroup.fr',
    'Lincoln': 'lincoln.fr',
    'Walters People': 'walterspeople.fr',
    'Robert Walters France': 'robertwalters.fr',

    # --- HR Tech & Paie ---
    'ADP France': 'adp.fr',
    'Cegid': 'cegid.com',
    'SD Worx France': 'sdworx.fr',
    'Workday France': 'workday.com',
    'Cornerstone OnDemand France': 'cornerstoneondemand.fr',
    'Silae': 'silae.fr',
    'Lucca': 'lucca.fr',
    'PayFit': 'payfit.com',
    'Sopra HR Software': 'soprahr.com',
    'Talentsoft': 'talentsoft.fr',
    'Eurecia': 'eurecia.com',

    # --- Formation & EdTech ---
    'Cegos': 'cegos.fr',
    'Demos': 'demos.fr',
    'Orsys': 'orsys.fr',
    'M2i Formation': 'm2iformation.fr',
    'Abilways': 'abilways.com',
    'Lefebvre Dalloz': 'lefebvre-dalloz.fr',
    'Galileo Global Education': 'galileo-gge.com',
    'Studi': 'studi.com',
    'IONIS Education Group': 'ionis-group.com',
    'Nexity Formation': 'nexity.fr',
    'AFPA': 'afpa.fr',
    'CESI': 'cesi.fr',
    'Openclassrooms': 'openclassrooms.com',
    'Docebo France': 'docebo.com',

    # --- Energie & Environnement ---
    'SUEZ': 'suez.com',
    'Veolia': 'veolia.com',
    'Saur': 'saur.com',
    'Derichebourg': 'derichebourg.com',
    'Paprec': 'paprec.com',
    'Seche Environnement': 'groupe-seche.com',
    'EDF': 'edf.fr',
    'ENGIE': 'engie.com',
    'ENGIE Solutions': 'engie-solutions.com',
    'Dalkia': 'dalkia.fr',
    'TotalEnergies': 'totalenergies.com',
    'Enedis': 'enedis.fr',
    'GRDF': 'grdf.fr',
    'RTE': 'rte-france.com',
    'Air Liquide': 'airliquide.com',
    'Arkema': 'arkema.com',
    'Solvay France': 'solvay.com',
    'Orano': 'orano.group',
    'Framatome': 'framatome.com',
    'CEA': 'cea.fr',
    'Rubis': 'rubis.fr',
    'Nexans': 'nexans.com',
    'Schneider Electric': 'se.com',
    'Legrand': 'legrandgroup.com',
    'Rexel': 'rexel.com',
    'Sonepar': 'sonepar.com',
    'Vinci Energies': 'vinci-energies.com',

    # --- Transport & Logistique ---
    'SNCF': 'sncf.com',
    'RATP': 'ratp.fr',
    'Keolis': 'keolis.com',
    'Transdev': 'transdev.com',
    'Geodis': 'geodis.com',
    'DHL France': 'dhl.fr',
    'FedEx France': 'fedex.com',
    'UPS France': 'ups.com',
    'DB Schenker France': 'dbschenker.com',
    'Kuehne+Nagel France': 'kuehne-nagel.com',
    'DSV France': 'dsv.com',
    'Bollore Logistics': 'bollore-logistics.com',
    'XPO Logistics France': 'xpo.com',
    'STEF': 'stef.com',
    'Dachser France': 'dachser.fr',
    'Air France-KLM': 'airfranceklm.com',
    'Groupe ADP': 'parisaeroport.fr',
    'Getlink': 'getlinkgroup.com',
    'CMA CGM': 'cmacgm-group.com',
    'Aeroports de Paris': 'parisaeroport.fr',

    # --- Banque ---
    'BNP Paribas': 'bnpparibas.com',
    'Societe Generale': 'societegenerale.com',
    'Credit Agricole': 'credit-agricole.com',
    'BPCE': 'groupebpce.com',
    'Banque Populaire': 'banquepopulaire.fr',
    "Caisse d'Epargne": 'caisse-epargne.fr',
    'Credit Mutuel': 'creditmutuel.fr',
    'CIC': 'cic.fr',
    'LCL': 'lcl.fr',
    'La Banque Postale': 'labanquepostale.fr',
    'HSBC France': 'hsbc.fr',
    'Boursorama': 'boursorama.com',
    'Natixis': 'natixis.com',
    'Amundi': 'amundi.com',
    'Caisse des Depots': 'caissedesdepots.fr',
    'Banque des Territoires': 'banquedesterritoires.fr',
    'Bpifrance': 'bpifrance.fr',
    'Oddo BHF': 'oddo-bhf.com',
    'Edmond de Rothschild France': 'edmond-de-rothschild.com',

    # --- Assurance & Protection sociale ---
    'AXA France': 'axa.fr',
    'Allianz France': 'allianz.fr',
    'Generali France': 'generali.fr',
    'CNP Assurances': 'cnp.fr',
    'Groupama': 'groupama.com',
    'MAIF': 'maif.fr',
    'MACIF': 'macif.fr',
    'Matmut': 'matmut.fr',
    'MAAF': 'maaf.fr',
    'Coveea': 'covea.eu',
    'Malakoff Humanis': 'malakoffhumanis.com',
    'AG2R La Mondiale': 'ag2rlamondiale.fr',
    'Klesia': 'klesia.fr',
    'Pro BTP': 'probtp.com',
    'Swiss Life France': 'swisslife.fr',
    'April': 'april.fr',
    'Verlingue': 'verlingue.fr',
    'WTW France': 'wtwco.com',
    'Marsh France': 'marsh.com',
    'Aon France': 'aon.com',
    'Verspieren': 'verspieren.com',
    'Harmonie Mutuelle': 'harmonie-mutuelle.fr',
    'Mutuelle Generale': 'lamutuellegenerale.fr',

    # --- Telecom & IT ---
    'Orange': 'orange.com',
    'Orange Business': 'orange-business.com',
    'Bouygues Telecom': 'bouyguestelecom.fr',
    'SFR': 'sfr.fr',
    'Altice France': 'alticefrance.com',
    'Iliad': 'iliad.fr',
    'Free Pro': 'freepro.com',
    'Worldline': 'worldline.com',
    'Ingenico': 'ingenico.com',
    'Edenred': 'edenred.com',
    'Sage France': 'sage.com',
    'Cegedim': 'cegedim.fr',
    'Dassault Systemes': '3ds.com',
    'Murex': 'murex.com',
    'Amadeus France': 'amadeus.com',
    'OVHcloud': 'ovhcloud.com',
    'Scaleway': 'scaleway.com',
    'Microsoft France': 'microsoft.com',
    'IBM France': 'ibm.com',
    'Oracle France': 'oracle.com',
    'SAP France': 'sap.com',
    'Salesforce France': 'salesforce.com',
    'Dell Technologies France': 'dell.com',
    'HP France': 'hp.com',
    'Cisco France': 'cisco.com',
    'Ricoh France': 'ricoh.fr',
    'Xerox France': 'xerox.com',
    'Canon France': 'canon.fr',
    'Konica Minolta France': 'konicaminolta.fr',

    # --- Services aux entreprises ---
    'Sodexo': 'sodexo.com',
    'Elior': 'eliorgroup.com',
    'Compass Group France': 'compass-group.fr',
    'API Restauration': 'api-restauration.com',
    'Newrest': 'newrest.eu',
    'Onet': 'groupeonet.com',
    'Atalian': 'atalian.com',
    'Samsic': 'samsic.fr',
    'GSF': 'gsf.fr',
    'ISS France': 'fr.issworld.com',
    'Securitas France': 'securitas.fr',
    'Fiducial': 'fiducial.fr',
    'Bureau Veritas': 'bureauveritas.fr',
    'SGS France': 'sgs.com',
    'Dekra France': 'dekra.fr',
    'Apave': 'apave.com',
    'Socotec': 'socotec.fr',
    'Manutan': 'manutan.fr',
    'Lyreco France': 'lyreco.com',
    'RAJA': 'raja.fr',
    'Bruneau': 'bruneau.fr',

    # --- Immobilier & Construction ---
    'Vinci': 'vinci.com',
    'Bouygues Construction': 'bouygues-construction.com',
    'Bouygues Immobilier': 'bouygues-immobilier.com',
    'Eiffage': 'eiffage.com',
    'Colas': 'colas.com',
    'Spie Batignolles': 'spiebatignolles.fr',
    'NGE': 'nge.fr',
    'Fayat': 'fayat.com',
    'Nexity': 'nexity.fr',
    'Icade': 'icade.fr',
    'Gecina': 'gecina.fr',
    'Klepierre': 'klepierre.com',
    'Unibail-Rodamco-Westfield': 'urw.com',
    'Covivio': 'covivio.eu',
    'Foncia': 'foncia.com',
    'BNP Paribas Real Estate': 'realestate.bnpparibas',
    'JLL France': 'jll.fr',
    'CBRE France': 'cbre.fr',
    'Cushman & Wakefield France': 'cushmanwakefield.com',
    'Saint-Gobain': 'saint-gobain.com',
    'Holcim France': 'holcim.fr',
    'Vicat': 'vicat.fr',
    'Point P': 'pointp.fr',
    'Cedeo': 'cedeo.fr',
    'SPIE': 'spie.com',

    # --- Industrie ---
    'Airbus': 'airbus.com',
    'Safran': 'safran-group.com',
    'Thales': 'thalesgroup.com',
    'Dassault Aviation': 'dassault-aviation.com',
    'Naval Group': 'naval-group.com',
    'ArcelorMittal France': 'arcelormittal.com',
    'Renault': 'renaultgroup.com',
    'Stellantis': 'stellantis.com',
    'Valeo': 'valeo.com',
    'Forvia': 'forvia.com',
    'Michelin': 'michelin.com',
    'Plastic Omnium': 'plasticomnium.com',
    'Alstom': 'alstom.com',
    'Wabtec France': 'wabteccorp.com',
    'Imerys': 'imerys.com',
    'Eramet': 'eramet.com',
    'Vallourec': 'vallourec.com',
    'Tarkett': 'tarkett.com',
    'Somfy': 'somfy.fr',
    'SEB': 'groupeseb.com',
    'Bic': 'bic.com',
    'Essilorluxottica': 'essilorluxottica.com',
    'STMicroelectronics': 'st.com',
    'Soitec': 'soitec.com',

    # --- Sante & Pharma ---
    'Sanofi': 'sanofi.com',
    'Servier': 'servier.com',
    'Ipsen': 'ipsen.com',
    'Pierre Fabre': 'pierre-fabre.com',
    'Biogaran': 'biogaran.fr',
    'Boehringer Ingelheim France': 'boehringer-ingelheim.com',
    'Novartis France': 'novartis.com',
    'Roche France': 'roche.fr',
    'Pfizer France': 'pfizer.fr',
    'MSD France': 'msd-france.com',
    'AstraZeneca France': 'astrazeneca.fr',
    'GSK France': 'gsk.com',
    'Bayer France': 'bayer.fr',
    'Johnson & Johnson France': 'jnj.com',
    'Abbott France': 'abbott.fr',
    'Becton Dickinson France': 'bd.com',
    'Medtronic France': 'medtronic.com',
    'Philips France': 'philips.fr',
    'GE HealthCare France': 'gehealthcare.fr',
    'Siemens Healthineers France': 'siemens-healthineers.com',
    'Clariane': 'clariane.com',
    'Ramsay Sante': 'ramsaysante.fr',
    'Elsan': 'elsan.care',
    'Vivalto Sante': 'vivalto-sante.com',
    'Eurofins': 'eurofins.fr',
    'Cerba HealthCare': 'cerbahealthcare.fr',
    'Biogroup': 'biogroup.fr',

    # --- Retail & Grande conso ---
    'Carrefour': 'carrefour.com',
    'Auchan': 'auchan.fr',
    'E.Leclerc': 'leclerc.com',
    'Les Mousquetaires': 'mousquetaires.com',
    'Casino': 'groupe-casino.fr',
    'Monoprix': 'monoprix.fr',
    'Systeme U': 'magasins-u.com',
    'Lidl France': 'lidl.fr',
    'Metro France': 'metro.fr',
    'Promocash': 'promocash.com',
    'Danone': 'danone.com',
    'Nestle France': 'nestle.fr',
    'Unilever France': 'unilever.fr',
    'Mondelez France': 'mondelezinternational.com',
    'PepsiCo France': 'pepsico.fr',
    'Coca-Cola Europacific France': 'cocacolaep.com',
    'Mars France': 'mars.com',
    'Ferrero France': 'ferrero.fr',
    'Lactalis': 'lactalis.fr',
    'Bel': 'groupe-bel.com',
    'Savencia': 'savencia.com',
    'Bonduelle': 'bonduelle.com',
    'Heineken France': 'heinekenfrance.fr',
    'Pernod Ricard': 'pernod-ricard.com',
    'Remy Cointreau': 'remy-cointreau.com',
    "L'Oreal": 'loreal.com',
    'Beiersdorf France': 'beiersdorf.fr',
    'Henkel France': 'henkel.fr',
    'Procter & Gamble France': 'pg.com',
    'Reckitt France': 'reckitt.com',
    'Yves Rocher': 'yves-rocher.fr',
    'Clarins': 'clarins.com',
    'Kering': 'kering.com',
    'LVMH': 'lvmh.fr',
    'Hermes': 'hermes.com',
    'Decathlon': 'decathlon.fr',
    'Fnac Darty': 'fnacdarty.com',
    'Leroy Merlin': 'leroymerlin.fr',
    'Castorama': 'castorama.fr',
    'Boulanger': 'boulanger.com',
    'But': 'but.fr',
    'Conforama': 'conforama.fr',
    'Maisons du Monde': 'maisonsdumonde.com',
    'Sephora': 'sephora.fr',
    'Veepee': 'veepee.com',
    'Cdiscount': 'cdiscount.com',

    # --- Tech & Scale-up ---
    'Criteo': 'criteo.com',
    'Doctolib': 'doctolib.fr',
    'BlaBlaCar': 'blablacar.fr',
    'Back Market': 'backmarket.fr',
    'Contentsquare': 'contentsquare.com',
    'Dataiku': 'dataiku.com',
    'Mirakl': 'mirakl.com',
    'Qonto': 'qonto.com',
    'Swile': 'swile.co',
    'Alan': 'alan.com',
    'Ledger': 'ledger.com',
    'ManoMano': 'manomano.fr',
    'Leboncoin': 'leboncoin.fr',
    'Ubisoft': 'ubisoft.com',
    'Believe': 'believe.com',
    'Deezer': 'deezer.com',
    'Malt': 'malt.fr',
    'Younited': 'younited-credit.com',
    'Lydia': 'lydia-app.com',
    'Pennylane': 'pennylane.com',

    # --- Medias & Communication ---
    'Publicis Groupe': 'publicisgroupe.com',
    'Havas': 'havas.com',
    'JCDecaux': 'jcdecaux.com',
    'Lagardere': 'lagardere.com',
    'TF1': 'groupe-tf1.fr',
    'M6': 'groupem6.fr',
    'France Televisions': 'francetelevisions.fr',
    'Radio France': 'radiofrance.com',
    'Canal+': 'canalplusgroup.com',
    'Prisma Media': 'prismamedia.com',
    'Le Monde': 'lemonde.fr',
    'Les Echos-Le Parisien': 'lesechos-leparisien.fr',
    'Webedia': 'webedia-group.com',
    'Teads': 'teads.com',
    'Ipsos': 'ipsos.com',
    'Kantar France': 'kantar.com',
    'Nielsen France': 'nielsen.com',

    # --- Secteur public & Parapublic ---
    'La Poste': 'legroupe.laposte.fr',
    'Docaposte': 'docaposte.com',
    'France Travail': 'francetravail.fr',
    'Urssaf Caisse Nationale': 'urssaf.fr',
    'CNAM': 'assurance-maladie.ameli.fr',
    'CNAF': 'caf.fr',
    'CNES': 'cnes.fr',
    'ONERA': 'onera.fr',
    'IFP Energies Nouvelles': 'ifpenergiesnouvelles.fr',
    'ADEME': 'ademe.fr',
    'Business France': 'businessfrance.fr',
    'Francaise des Jeux': 'groupefdj.com',
    'PMU': 'pmu.fr',
    'Voies Navigables de France': 'vnf.fr',
}


def domaine(nom):
    """Domaine connu, sinon None."""
    return DOMAINES.get(nom.strip())
